article/urls.py
from django.urls import path
from . import views

app_name = 'article'
urlpatterns = [
    path('', views.article_list, name='home'),  # 主页，显示文章列表
    path('article/<slug:slug>/', views.article_detail, name='article_detail'),  # 文章详情页
    path('about/', views.about_view, name='about'),  # 文章详情页
    path('contact/', views.contact_view, name='contact'),  # 文章详情页
    path('error/', views.error_view),  # 错误页
]

article/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.utils import timezone
from mdeditor.fields import MDTextField


def generate_random_slug():
    return str(uuid.uuid4())[:8]  # 生成一个8字符长的随机slug


class Article(models.Model):
    title = models.CharField(max_length=200, verbose_name="文章标题")  # 文章标题
    slug = models.SlugField(max_length=200, unique=True, blank=True, default=generate_random_slug,
                            verbose_name="URL别名")  # 设置默认slug值
    summary = models.TextField(max_length=500, verbose_name="文章摘要")  # 文章摘要
    content = MDTextField(verbose_name="文章内容")  # 文章内容
    published_date = models.DateTimeField(default=timezone.now, verbose_name="发布时间")  # 发布时间
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")  # 创建时间
    updated_date = models.DateTimeField(auto_now=True, verbose_name="更新时间")  # 更新时间

    class Meta:
        ordering = ['-published_date']  # 按发布时间降序排序
        verbose_name = "文章"
        verbose_name_plural = "文章"
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article_detail', args=[self.slug])  # 生成文章详情页的URL

    def save(self, *args, **kwargs):
        if not self.slug:  # 如果slug为空，则设置默认值
            self.slug = generate_random_slug()
        super().save(*args, **kwargs)

article/views.py
import markdown
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import render, get_object_or_404

from .models import Article


def article_list(request):
    articles = Article.objects.all()  # 获取所有文章
    paginator = Paginator(articles, 5)  # 每页显示5篇文章
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'articles': page_obj, 'title': '文章首页'}
    return render(request, 'blog/article_list.html', context)


def article_detail(request, slug):
    article = get_object_or_404(Article, slug=slug)  # 根据slug获取对应的文章

    # 将markdown语法渲染成html样式
    article.content = markdown.markdown(article.content,
                                        extensions=[
                                            # 包含 缩写、表格等常用扩展
                                            'markdown.extensions.extra',
                                            # 语法高亮扩展
                                            'markdown.extensions.codehilite',
                                            'markdown.extensions.tables',
                                        ])

    context = {'article': article, 'title': article.title}

    return render(request, 'blog/article_detail.html', context)


def about_view(request):
    context = {
        'title': '关于我',
    }
    return render(request, 'blog/about.html',context)


def contact_view(request):
    context = {
        'title': '联系我',
    }
    return render(request, 'blog/contact.html',context)


def error_view(request):
    raise Http404("这是一个人为抛出的404错误")

article/templates/blog/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<!-- header -->
{% include "blog/header.html" %}

<!-- 导航栏 -->
{% include "blog/navbar.html" %}

<body>

<main class="container mt-4">
    <h1>关于我</h1>
    <p>您好！我是一名充满热情的Python开发工程师。</p>

    <p>
        我熟练掌握Python语言，并且对C语言也有很好的掌握，此外还了解C++、Java和JavaScript等多种编程语言。
    </p>

</main>

{% include "blog/footer.html" %}

<script src="{% static 'blog/js/jquery-3.5.1.slim.min.js' %}"></script>
<script src="{% static 'blog/js/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/4.5.3/js/bootstrap.min.js' %}"></script>

</body>
</html>

article/templates/blog/article_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<!-- header -->
{% include "blog/header.html" %}

<!-- 导航栏 -->
{% include "blog/navbar.html" %}
<link rel="stylesheet" href="{% static 'blog/css/code.css' %}" >
<body>

<main class="container mt-4">
    <article>
        <h1>{{ article.title }}</h1>
        <p><small>发表于 {{ article.published_date }}</small></p>
        <div class="content">
            {{ article.content|safe }}
        </div>
    </article>
</main>

 {% include "blog/footer.html" %}

    <script src="{% static 'blog/js/jquery-3.5.1.slim.min.js' %}"></script>
    <script src="{% static 'blog/js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/4.5.3/js/bootstrap.min.js' %}"></script>


</body>
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
    showProcessingMessages: false, //关闭js加载过程信息
    messageStyle: "none", //不显示信息
    extensions: ["tex2jax.js"],
    jax: ["input/TeX", "output/HTML-CSS"],
    tex2jax: {
        inlineMath:  [ ["$", "$"] ], //行内公式选择$
        displayMath: [ ["$$","$$"] ], //段内公式选择$$
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre','code','a'], //避开某些标签
        ignoreClass:"comment-content" //避开含该Class的标签
    },
    "HTML-CSS": {
        availableFonts: ["STIX","TeX"], //可选字体
        showMathMenu: false //关闭右击菜单显示
    }
});
MathJax.Hub.Queue(["Typeset",MathJax.Hub]);

</script>

<script src="{% static 'blog/js/MathJax.js' %}"></script>
{#<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>#}
</html>

article/templates/blog/article_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- header -->
{% include "blog/header.html" %}

<!-- 导航栏 -->
{% include "blog/navbar.html" %}

<body>


<!-- 文章列表 -->
<main class="container mt-4">
    <h1>最新文章</h1>
    <div class="row">
        {% for article in articles %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title"><a
                                href="{% url 'article:article_detail' article.slug %}">{{ article.title }}</a></h5>
                        <p class="card-text">{{ article.summary }}</p>
                        <p class="card-text"><small class="text-muted">发表于 {{ article.published_date }}</small></p>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>暂无文章。</p>
        {% endfor %}
    </div>

    <!-- 分页 -->
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if articles.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; 第一页</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}">上一页</a>
                </li>
            {% endif %}

            <li class="page-item disabled"><span
                    class="page-link">第 {{ articles.number }} 页，共 {{ articles.paginator.num_pages }} 页</span></li>

            {% if articles.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ articles.next_page_number }}">下一页</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ articles.paginator.num_pages }}">最后一页
                    &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
</main>

<!-- 底部信息 -->
{% include "blog/footer.html" %}

<!-- 引入Bootstrap的JavaScript文件 -->
<script src="{% static 'blog/js/jquery-3.5.1.slim.min.js' %}"></script>
<script src="{% static 'blog/js/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/4.5.3/js/bootstrap.min.js' %}"></script>
</body>
</html>

article/templates/blog/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<!-- header -->
{% include "blog/header.html" %}

<!-- 导航栏 -->
{% include "blog/navbar.html" %}

<body>

<main class="container mt-4">
    <h1>联系我</h1>
    <b><p>电子邮件：hongzhe2022@163.com</p></b>

</main>

{% include "blog/footer.html" %}

<script src="{% static 'blog/js/jquery-3.5.1.slim.min.js' %}"></script>
<script src="{% static 'blog/js/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/4.5.3/js/bootstrap.min.js' %}"></script>
</body>
</html>

article/templates/blog/footer.html
<footer class="bg-light text-center py-4 mt-4">
    <p>&copy; 2024 红掌拨清波的博客. 保留所有权利。</p>
</footer>

article/templates/blog/header.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <!-- 引入Bootstrap的CSS文件 -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}" >
    <noscript><link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}"></noscript>
    <style>
        html, body {
            height: 100%;
            margin: 0;
        }
        body {
            display: flex;
            flex-direction: column;
        }
        main {
            flex: 1;
        }
        footer {
            background-color: #f8f9fa;
            text-align: center;
            padding: 1rem;
        }
    </style>
</head>

article/templates/blog/navbar.html
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!-- 统一品牌链接，可以根据当前页面动态设定 -->
        <a class="navbar-brand" href="{% url 'article:home' %}">首页</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <!-- 主要导航项，包含通用链接 -->
            <ul class="navbar-nav mr-auto">
{#                <li class="nav-item"><a class="nav-link" href="{% url 'article:home' %}">首页</a></li>#}
                <li class="nav-item"><a class="nav-link" href="{% url 'article:about' %}">关于</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'article:contact' %}">联系</a></li>
            </ul>
        </div>
    </nav>
</header>